[colors.primary]
background = '#17120f'
foreground = '#ebe0d9'
 
[colors.cursor]
text = '#ebe0d9'
cursor = '#d5c3b6' 
 
[colors.vi_mode_cursor]
text = '#17120f'
cursor = '#ffb874' 
 
[colors.search.matches]
foreground = '#51443a' 
background = '#c1cc99' 
 
[colors.search.focused_match]
foreground = '#51443a' 
background = '#ffb874' 
 
[colors.footer_bar]
foreground = '#51443a' 
background = '#ebe0d9' 
 
[colors.hints.start]
foreground = '#51443a' 
background = '#e2c0a4' 
 
[colors.hints.end]
foreground = '#51443a' 
background = '#e2c0a4' 
 
[colors.selection]
text = '#17120f'
background = '#ffb874'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb874' 
yellow = '#8c5000' 
blue = '#ffb874' 
magenta = '#c1cc99' 
cyan = '#e2c0a4' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 